import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Sussuros do Baralho',
  description: 'Generated by Gabriel Borges',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='fade'>{children}</body>
    </html>
  )
}
